[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"

[env]
UPLOAD_DIR = "uploads"
RESULTS_DIR = "results"
PYTHONPATH = "/app:/app/web-app/backend"